/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IAntDesignDeleteOutlined: typeof import('~icons/ant-design/delete-outlined')['default']
    IAntDesignDownloadOutlined: typeof import('~icons/ant-design/download-outlined')['default']
    IAntDesignFontSizeOutlined: typeof import('~icons/ant-design/font-size-outlined')['default']
    IAntDesignLeftOutlined: typeof import('~icons/ant-design/left-outlined')['default']
    IAntDesignMenuOutlined: typeof import('~icons/ant-design/menu-outlined')['default']
    IAntDesignMinusOutlined: typeof import('~icons/ant-design/minus-outlined')['default']
    IAntDesignPlusOutlined: typeof import('~icons/ant-design/plus-outlined')['default']
    IAntDesignRightOutlined: typeof import('~icons/ant-design/right-outlined')['default']
    IAntDesignSelectOutlined: typeof import('~icons/ant-design/select-outlined')['default']
    IAntDesignUploadOutlined: typeof import('~icons/ant-design/upload-outlined')['default']
  }
}
